# Generated by Django 5.0.6 on 2025-04-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinder_garden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclasses',
            name='children',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
